# Generated by Django 4.0.4 on 2023-11-24 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supply_chains', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSAlerts',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='ABCDEFGHJKMNPQRSTUVWXYZ23456789', min_length=10, prefix='', primary_key=True, serialize=False)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Updated On')),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('response', models.JSONField(blank=True, null=True)),
                ('response_text', models.TextField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='ABCDEFGHJKMNPQRSTUVWXYZ23456789', min_length=10, prefix='', primary_key=True, serialize=False)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Updated On')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is read?')),
                ('visibility', models.BooleanField(default=True, verbose_name='Visibility')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('title_en_us', models.CharField(max_length=300, null=True, verbose_name='Title')),
                ('title_en_uk', models.CharField(max_length=300, null=True, verbose_name='Title')),
                ('title_fr', models.CharField(max_length=300, null=True, verbose_name='Title')),
                ('title_nl', models.CharField(max_length=300, null=True, verbose_name='Title')),
                ('body', models.CharField(max_length=500, verbose_name='Body')),
                ('body_en_us', models.CharField(max_length=500, null=True, verbose_name='Body')),
                ('body_en_uk', models.CharField(max_length=500, null=True, verbose_name='Body')),
                ('body_fr', models.CharField(max_length=500, null=True, verbose_name='Body')),
                ('body_nl', models.CharField(max_length=500, null=True, verbose_name='Body')),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name='Action URL')),
                ('action_push', models.BooleanField(default=False, verbose_name='Push Notification')),
                ('action_sms', models.BooleanField(default=False, verbose_name='Sms Notification')),
                ('action_email', models.BooleanField(default=False, verbose_name='Email Notification')),
                ('event_id', models.PositiveIntegerField(blank=True, null=True)),
                ('redirect_id', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Redirect ID')),
                ('redirect_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Redirect type')),
                ('type', models.CharField(max_length=100, verbose_name='Type')),
                ('context', models.JSONField(blank=True, null=True, verbose_name='Context')),
                ('send_to', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Send To')),
                ('aws_sms_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='AWS SMS ID')),
                ('actor_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='supply_chains.company', verbose_name='Actor Entity')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('event_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_event_types', to='contenttypes.contenttype', verbose_name='Event Type')),
                ('target_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='supply_chains.company', verbose_name='Target Entity')),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('validation_token', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification', to='accounts.validationtoken', verbose_name='Validation Token')),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
    ]
