# Generated by Django 4.0.4 on 2023-11-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicy',
            name='content_ind',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Policy Content'),
        ),
    ]
