# Generated by Django 4.0.4 on 2023-12-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_privacypolicy_content_ind'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allow_multiple_login',
            field=models.BooleanField(default=True, verbose_name='Allow Multiple Login'),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
    ]
