# Generated by Django 4.0.4 on 2023-12-20 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_allow_multiple_login_userdevice_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='allow_multiple_login',
        ),
    ]
