# Generated by Django 4.0.4 on 2023-12-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_allow_multiple_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='device_loc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Device Location'),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='device_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Device Name'),
        ),
    ]
