# Generated by Django 4.0.4 on 2024-02-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userdevice_device_loc_userdevice_device_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Device Version'),
        ),
    ]
