# Generated by Django 4.0.4 on 2023-11-24 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='ABCDEFGHJKMNPQRSTUVWXYZ23456789', min_length=10, prefix='', primary_key=True, serialize=False)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Updated On')),
                ('form_type', models.CharField(choices=[('TRANSACTION', 'Transaction'), ('FARMER', 'Farmer'), ('PAYMENT', 'Payment'), ('PRODUCT', 'Product')], default='TRANSACTION', max_length=20, verbose_name='Form Type')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='ABCDEFGHJKMNPQRSTUVWXYZ23456789', min_length=10, prefix='', primary_key=True, serialize=False)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Updated On')),
                ('label', models.CharField(max_length=100, verbose_name='Label')),
                ('type', models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('EMAIL', 'Email'), ('PHONE', 'Phone'), ('DATE', 'Date'), ('BOOLEAN', 'Boolean')], max_length=20, verbose_name='Field Type')),
                ('required', models.BooleanField(default=True, verbose_name='Required')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms.form', verbose_name='Form')),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='ABCDEFGHJKMNPQRSTUVWXYZ23456789', min_length=10, prefix='', primary_key=True, serialize=False)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Updated On')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='forms.form', verbose_name='Form')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='catalogs.product', verbose_name='Product')),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubmissionValues',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='ABCDEFGHJKMNPQRSTUVWXYZ23456789', min_length=10, prefix='', primary_key=True, serialize=False)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Updated On')),
                ('value', models.CharField(max_length=100, verbose_name='Value')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='forms.formfield', verbose_name='Field')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='forms.submission', verbose_name='Submission')),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
        ),
    ]
