# Generated by Django 4.0.4 on 2023-11-24 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supply_chains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='supply_chains.company', verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='form',
            name='updater',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL, verbose_name='Updater'),
        ),
        migrations.AddConstraint(
            model_name='submissionvalues',
            constraint=models.UniqueConstraint(fields=('submission', 'field'), name='unique_submission_field'),
        ),
    ]
