# Generated by Django 4.0.4 on 2023-11-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_formfield_default_value_formfield_label_en_uk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Key'),
        ),
    ]
