# Generated by Django 4.0.4 on 2023-11-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_initial'),
        ('forms', '0005_alter_formfield_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='product',
        ),
        migrations.AddField(
            model_name='submission',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='submissions', to='catalogs.product', verbose_name='Products'),
        ),
    ]
