# Generated by Django 4.0.4 on 2023-12-06 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0007_remove_submission_products_submission_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFieldConfig',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='ABCDEFGHJKMNPQRSTUVWXYZ23456789', min_length=10, prefix='', primary_key=True, serialize=False)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Updated On')),
                ('label', models.CharField(max_length=100, verbose_name='Label')),
                ('key', models.CharField(max_length=100, verbose_name='Key')),
                ('visibility', models.BooleanField(default=True, verbose_name='Visibility')),
                ('required', models.BooleanField(default=False, verbose_name='Required')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_config', to='forms.form', verbose_name='Form')),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
        ),
        migrations.AddConstraint(
            model_name='formfieldconfig',
            constraint=models.UniqueConstraint(fields=('form', 'key'), name='unique_form_field_config'),
        ),
    ]
