"""Django settings for trace_connect project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path
from pickle import FALSE

import sentry_sdk
from sentry_sdk.integrations.celery import CeleryIntegration
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.redis import RedisIntegration

from . import env

ENVIRONMENT = env.get("ENVIRONMENT")
DEPLOYMENT = env.get("DEPLOYMENT")
ENTERPRISE_MODE = False

ROOT_URL = env.get("ROOT_URL")
FRONT_ROOT_URL = env.get("FRONT_ROOT_URL")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    ROOT_URL,
    "localhost",
    "127.0.0.1",
    "django",
]


# Application definition

INSTALLED_APPS = [
    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "oauth2_provider",
    "corsheaders",
    # External Core Libraries
    "rest_framework",
    "rest_framework.authtoken",
    "dj_rest_auth",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    # 'fcm_django',
    # External utility libraries
    "django_extensions",
    "modeltranslation",
    "phonenumber_field",
    "admin_extra_buttons",
    "django_otp",
    "django_otp.plugins.otp_totp",
    # Internal Apps (V1)
    "v1.accounts",
    "v1.oauth",
    "v1.apiauth",
    "v1.notifications",
    "v1.catalogs",
    "v1.forms",
    "v1.supply_chains",
    "v1.transactions",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # CORS header middlewares
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django_otp.middleware.OTPMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.locale.LocaleMiddleware",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "base.authentication.CustomDynamicAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("base.permissions.CombinedPermission",),
    "DEFAULT_THROTTLE_CLASSES": ["rest_framework.throttling.AnonRateThrottle"],
    "DEFAULT_THROTTLE_RATES": {"anon": "5/min"},
    "EXCEPTION_HANDLER": ("base.exceptions.exception_handler.custom_exception_handler"),
    "DATETIME_FORMAT": "%s",
    "DEFAULT_PAGINATION_CLASS": ("rest_framework.pagination.LimitOffsetPagination"),
    "PAGE_SIZE": 10,
    "DEFAULT_RENDERER_CLASSES": ("base.request_handler.response.ApiRenderer",),
    "DEFAULT_FILTER_BACKENDS": ("django_filters.rest_framework.DjangoFilterBackend",),
    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.URLPathVersioning",
    "DEFAULT_SCHEMA_CLASS": "rest_framework.schemas.coreapi.AutoSchema",
}

# AUTHENTICATION_BACKENDS = (
#     "django.contrib.auth.backends.ModelBackend",  # To keep the Browsable API
#     "oauth2_provider.backends.OAuth2Backend",
# )

OAUTH2_PROVIDER_APPLICATION_MODEL = "oauth.ClientServer"
OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL = "oauth.ClientAccessToken"
OAUTH2_PROVIDER_ID_TOKEN_MODEL = "oauth.ClientIDToken"
OAUTH2_PROVIDER_REFRESH_TOKEN_MODEL = "oauth.ClientRefreshToken"
OAUTH2_PROVIDER_AUTH_SCOPE = "auth:user"

OAUTH2_PROVIDER = {
    "APPLICATION_ADMIN_CLASS": "v1.oauth.admin.ClientServerAdmin",
    "ACCESS_TOKEN_ADMIN_CLASS": "v1.oauth.admin.ClientAccessTokenAdmin",
    "OAUTH2_VALIDATOR_CLASS": ("v1.oauth.validators.OAuth2ClientAccessValidator"),
    "SCOPES": {
        "read:farmer": "Read Farmer",
        "create:farmer": "Create Farmer",
        "update:farmer": "Update Farmer",
        "delete:farmer": "Delete Farmer",
        "read:company": "Read Company",
        "create:company": "Create Company",
        "update:company": "Update Company",
        "delete:company": "Delete Company",
        "read:catalog": "Read Catalog",
        "create:catalog": "Create Catalog",
        "update:catalog": "Update Catalog",
        "delete:catalog": "Delete Catalog",
        "read:user": "Read User",
        "create:user": "Create User",
        "update:user": "Update User",
        "delete:user": "Delete User",
        "auth:user": "Auth User",
        "read:transaction": "Read Transactions",
        "create:transaction": "Create Transactions",
        "update:transaction": "Update Transactions",
        "delete:transaction": "Delete Transactions",
        "read:payment": "Read Payment",
        "create:payment": "Create Payment",
        "update:payment": "Update Payment",
        "delete:payment": "Delete Payment",
    },
}


REST_USE_JWT = True
JWT_AUTH_COOKIE = "rightorigins-v3-auth"
JWT_AUTH_REFRESH_COOKIE = "rightorigins-v3-refresh-token"


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=2),
    "REFRESH_TOKEN_LIFETIME": timedelta(weeks=100),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": (
        "rest_framework_simplejwt.authentication.default_user_authentication_rule"
    ),
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
}

ROOT_URLCONF = "trace_connect.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "trace_connect.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env.get("DB_NAME"),
        "USER": env.get("DB_USER"),
        "PASSWORD": env.get("DB_PASSWORD"),
        "PORT": env.get("DB_PORT", default="5432"),
        "HOST": env.get("DB_HOST", default="localhost"),
        "DISABLE_SERVER_SIDE_CURSORS": True,
    }
}

REDIS_URL = env.get("REDIS_URL", default="redis://127.0.0.1")
REDIS_PORT = env.get("REDIS_PORT", default=6379)

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"{REDIS_URL}:{REDIS_PORT}/1",
        "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
        "KEY_PREFIX": "trace_connect_django",
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation"
            ".UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": ("django.contrib.auth.password_validation.MinimumLengthValidator"),
    },
    {
        "NAME": ("django.contrib.auth.password_validation" ".CommonPasswordValidator"),
    },
    {
        "NAME": ("django.contrib.auth.password_validation" ".NumericPasswordValidator"),
    },
]

AUTH_USER_MODEL = "accounts.CustomUser"

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_THOUSAND_SEPARATOR = True
USE_I18N = True
USE_L10N = True

USE_TZ = True

LOCALE_PATHS = (BASE_DIR / "locale",)
LANGUAGES = [
    ("en-us", "English US"),
    ("en-uk", "English UK"),
    ("fr", "French"),
    ("nl", "Dutch"),
    ("id", "Indonesian"),
]

MODELTRANSLATION_DEFAULT_LANGUAGE = "en-us"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = env.get("STATIC_URL_PATH", default="static/")
STATIC_ROOT = BASE_DIR / "static"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Hash id encoding.

HASHID_SALT = env.get("HASHID_SALT")
HASHID_FIELD_SALT = env.get("HASHID_SALT")
HASHID_MIN_LENGTH = 10
HASHID_FIELD_MIN_LENGTH = 10
HASHID_ALPHABETS = "ABCDEFGHJKMNPQRSTUVWXYZ23456789"
HASHID_FIELD_ALPHABET = "ABCDEFGHJKMNPQRSTUVWXYZ23456789"
HASHID_FIELD_ALLOW_INT_LOOKUP = True
DEFAULT_AUTO_FIELD = "hashid_field.HashidAutoField"

ACCESS_TOKEN_LENGTH = 90
OTP_LENGTH = 6

# Cors setup

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_METHODS = ("GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS")
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-disposition",
    "content-type",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "user-id",
    "entity-id",
    "token",
    "language",
    "timezone",
]

CORS_PREFLIGHT_MAX_AGE = 86400
CORS_ALLOW_CREDENTIALS = True

CUSTOM_INSPECTORS = [
    "base.drf.swagger.inspectors.HashidFieldInspector",
]

SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "scheme": "bearer",
        }
    },
    "DEFAULT_API_URL": ROOT_URL,
    "DEFAULT_FIELD_INSPECTORS": [
        "base.drf.swagger.inspectors.HashidFieldInspector",
        "drf_yasg.inspectors.CamelCaseJSONFilter",
        "drf_yasg.inspectors.RecursiveFieldInspector",
        "drf_yasg.inspectors.ReferencingSerializerInspector",
        "drf_yasg.inspectors.ChoiceFieldInspector",
        "drf_yasg.inspectors.FileFieldInspector",
        "drf_yasg.inspectors.DictFieldInspector",
        "drf_yasg.inspectors.JSONFieldInspector",
        "drf_yasg.inspectors.HiddenFieldInspector",
        "drf_yasg.inspectors.RelatedFieldInspector",
        "drf_yasg.inspectors.SerializerMethodFieldInspector",
        "drf_yasg.inspectors.SimpleFieldInspector",
        "drf_yasg.inspectors.StringDefaultFieldInspector",
    ],
    # 'DEFAULT_FIELD_INSPECTORS': CUSTOM_INSPECTORS + list(
    # swagger_settings.DEFAULT_FIELD_INSPECTORS),
}


# Email setup

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = env.get("EMAIL_HOST")
EMAIL_PORT = env.get("EMAIL_PORT")
EMAIL_HOST_USER = env.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env.get("EMAIL_HOST_PASSWORD")
FROM_EMAIL = EMAIL_HOST_USER
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False


# celery setup

CELERY_BROKER_URL = f"{REDIS_URL}:{REDIS_PORT}"
CELERY_RESULT_BACKEND = f"{REDIS_URL}:{REDIS_PORT}"
CELERY_TIMEZONE = "UTC"
CELERY_DEFAULT_QUEUE = "low"
CELERY_ROUTES = {
    "send_email": {"queue": "high"},
    "send_sms": {"queue": "high"},
}
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

sentry_sdk.init(
    dsn=env.get("SENTRY_DSN"),
    integrations=[
        DjangoIntegration(),
        CeleryIntegration(),
        RedisIntegration(),
    ],
    traces_sample_rate=1.0,
    environment=ENVIRONMENT,
    _experiments={
        "profiles_sample_rate": 1.0,
    },
)
sentry_sdk.set_tag("deployment", DEPLOYMENT)

AUTH_TYPE_CLASSES = {
    'password_grant': 'base.authentication.JWTAuthentication',
    'client_credentials': 'base.authentication.OAuth2Authentication',
}

TRACE_URL = env.get("TRACE_URL")
CONNECT_LOGIN_URL = ROOT_URL + "/v1/auth/login/"

CONNECT_AUTHENTICATION_METHOD = {
    "type": "username_password",
    "description": "Login with username and password",
    "url": CONNECT_LOGIN_URL,
    "auth_type": "password_grant",
}

SERVER_NAME = env.get("SERVER_NAME")
SSO_ENABLED = env.get("SSO_ENABLED", default="0")
CONNECT_REQUEST_SECURITY_INFO = {"nonce_required": True, "hmac_algorithm": "HMAC-SHA256"}
FARMER_CONSENT_WEBHOOK_URL = env.get("FARMER_CONSENT_WEBHOOK_URL")

TOTP_TOKEN = env.get("TOTP_TOKEN")

if SSO_ENABLED == "1":
    CONNECT_AUTHENTICATION_METHOD = {
        "type": "oauth2",
        "description": "Login with Single Sign-On",
        "sso_login_url": env.get("SSO_LOGIN_URL"),
        "client_id": env.get("SSO_AUDIENCE"),
        "response_type": env.get("SSO_AUTH_RESPONSE_TYPE", default="code"),
        "app_type": env.get("SSO_AUTH_APP_TYPE", default="Connect"),
        "code_challenge_method": env.get("SSO_AUTH_CHALLENGE_METHOD", default="S256"),
        "sso_token_url": env.get("SSO_TOKEN_URL"),
        "sso_revoke_token_url": env.get("SSO_REVOKE_TOKEN_URL"),
        "sso_logout_url": env.get("SSO_LOGOUT_URL"),
        "auth_type": "external_auth",
    }

    SSO_AUTH = {
        "ALGORITHM": "RS256",
        "AUDIENCE": env.get("SSO_AUDIENCE"),
        "ISSUER": env.get("SSO_TOKEN_ISSUER"),
        "LEEWAY": 0,
        "AUTH_HEADER_TYPES": ("Bearer",),
        "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
        "USER_ID_FIELD": "email",
        "USER_ID_CLAIM": "email",
        "AUTH_TOKEN_CLASSES": ("base.sso.tokens.AccessToken",),
        "TOKEN_TYPE_CLAIM": None,
        "JTI_CLAIM": "jti",
        "VERFIFICATION_FILE_PATH": os.path.join(BASE_DIR, "public-key.pem")
    }

    SSO_SETTINGS_DOC_URL = env.get("SSO_SETTINGS_DOC_URL", default="")


    AUTH_TYPE_CLASSES['external_auth'] = 'base.sso.authentication.SSOJWTAuthentication'
    VALIDATE_HMAC_SIGNATURE = False
