# Generated by Django 4.0.4 on 2023-12-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0005_companyproduct_is_active_alter_entity_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference Number'),
        ),
    ]
