# Generated by Django 4.0.4 on 2023-12-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0007_companyproduct_allow_multiple_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyproduct',
            name='allow_multiple_login',
        ),
        migrations.AddField(
            model_name='company',
            name='allow_multiple_login',
            field=models.BooleanField(default=True, verbose_name='Allow Multiple Login'),
        ),
    ]
