# Generated by Django 4.0.4 on 2024-05-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0008_remove_companyproduct_allow_multiple_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='only_connect',
            field=models.BooleanField(default=False, verbose_name='Only Connect'),
        ),
    ]
