# Generated by Django 4.0.4 on 2024-08-12 18:57

from django.db import migrations, models
import v1.supply_chains.validators


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0009_entity_only_connect'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='geo_json',
            field=models.JSONField(blank=True, null=True, validators=[v1.supply_chains.validators.validate_geojson_polygon, v1.supply_chains.validators.validate_coordinates]),
        ),
    ]
