# Generated by Django 4.0.4 on 2024-08-23 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0010_farmer_geo_json'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entitycard',
            options={'ordering': ('-created_on',)},
        ),
        migrations.RemoveConstraint(
            model_name='entitycard',
            name='unique_entity_card',
        ),
    ]
