# Generated by Django 4.0.4 on 2024-10-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0011_alter_entitycard_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='meta_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
