# Generated by Django 4.0.4 on 2024-12-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0012_farmer_meta_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='theme_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Theme Info'),
        ),
    ]
