# Generated by Django 4.0.4 on 2024-12-11 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0015_alter_externalservice_service_url_entitybuyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='buyer',
        ),
    ]
