# Generated by Django 4.0.4 on 2025-03-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0016_remove_entity_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='make_farmers_private',
            field=models.BooleanField(default=False),
        ),
    ]
