# Generated by Django 4.0.4 on 2024-08-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_clientserver_allowed_origins_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientserver',
            name='allowed_origins',
        ),
        migrations.RemoveField(
            model_name='clientserver',
            name='hash_client_secret',
        ),
        migrations.AlterField(
            model_name='clientaccesstoken',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='clientserver',
            name='post_logout_redirect_uris',
            field=models.TextField(blank=True, help_text='Allowed Post Logout URIs list, space separated'),
        ),
    ]
