# Generated by Django 4.0.4 on 2023-12-04 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basetransaction',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created On'),
        ),
    ]
