# Generated by Django 4.0.4 on 2024-05-17 05:37

from django.db import migrations, models




class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_paymenttransaction_selected_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttransaction',
            name='base_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='producttransaction',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
