# Generated by Django 4.0.4 on 2024-02-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_paymenttransaction_selected_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference'),
        ),
    ]
