# Generated by Django 4.0.4 on 2024-02-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_producttransaction_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttransaction',
            name='send_seperately',
            field=models.BooleanField(default=False, verbose_name='Send seperately'),
        ),
    ]
