# Generated by Django 4.0.4 on 2024-05-29 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_producttransaction_base_price_and_more'),
        ('transactions', '0005_producttransaction_send_seperately'),
    ]

    operations = [
    ]
