# Generated by Django 4.0.4 on 2024-07-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_merge_20240529_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
    ]
