# Generated by Django 4.0.4 on 2023-11-24 07:00

import base.db.utilities
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectCard',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='ABCDEFGHJKMNPQRSTUVWXYZ23456789', min_length=10, prefix='', primary_key=True, serialize=False)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Updated On')),
                ('display_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Display ID')),
                ('card_id', models.CharField(max_length=100, unique=True, verbose_name='Card ID')),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='ABCDEFGHJKMNPQRSTUVWXYZ23456789', min_length=10, prefix='', primary_key=True, serialize=False)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Updated On')),
                ('name', models.CharField(max_length=1000, verbose_name='Country Name')),
                ('latitude', models.CharField(blank=True, max_length=500, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=500, null=True, verbose_name='Longitude')),
                ('alpha_2', models.CharField(blank=True, max_length=10, null=True, verbose_name='Country Code')),
                ('alpha_3', models.CharField(blank=True, max_length=10, null=True, verbose_name='CCA3 Country Code')),
                ('dial_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dial Code')),
                ('language', models.CharField(choices=[('en', 'English'), ('nl', 'Dutch'), ('de', 'German'), ('fr', 'French')], default='en', max_length=10, verbose_name='Selected Language')),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='ABCDEFGHJKMNPQRSTUVWXYZ23456789', min_length=10, prefix='', primary_key=True, serialize=False)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Updated On')),
                ('name', models.CharField(max_length=1000, verbose_name='Currency Name')),
                ('code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Currency Code')),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='ABCDEFGHJKMNPQRSTUVWXYZ23456789', min_length=10, prefix='', primary_key=True, serialize=False)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Updated On')),
                ('category', models.CharField(choices=[('PAYOUT', 'Payout Premium'), ('TRANSACTION', 'Transaction Premium')], default='TRANSACTION', max_length=11, verbose_name='Premium Category')),
                ('name', models.CharField(max_length=100, verbose_name='Premium Name')),
                ('type', models.CharField(choices=[('PER_TRANSACTION', 'Per Transaction'), ('PER_KG', 'Per KG'), ('PER_UNIT_CURRENCY', 'Per Unit Currency'), ('PER_FARMER', 'Per Farmer')], default='PER_UNIT_CURRENCY', max_length=17, verbose_name='Premium Type')),
                ('amount', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Amount')),
                ('included', models.BooleanField(default=True, verbose_name='Included')),
                ('dependant_on_card', models.BooleanField(default=False, verbose_name='Dependant on Card')),
                ('applicable_activity', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='BUY', max_length=4, verbose_name='Applicable Activity')),
                ('calculation_type', models.CharField(choices=[('NORMAL', 'Normal'), ('MANUAL', 'Manual'), ('OPTIONS', 'Options')], default='NORMAL', max_length=7, verbose_name='Calculation Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='ABCDEFGHJKMNPQRSTUVWXYZ23456789', min_length=10, prefix='', primary_key=True, serialize=False)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Updated On')),
                ('name', models.CharField(max_length=1000, verbose_name='Province Name')),
                ('latitude', models.CharField(blank=True, max_length=500, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=500, null=True, verbose_name='Longitude')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='catalogs.country', verbose_name='Country')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
            options={
                'ordering': ['country__name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='ABCDEFGHJKMNPQRSTUVWXYZ23456789', min_length=10, prefix='', primary_key=True, serialize=False)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Updated On')),
                ('name', models.CharField(max_length=500, verbose_name='Product Name')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Product Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to=base.db.utilities.get_file_path, verbose_name='Product Image')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PremiumOption',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='ABCDEFGHJKMNPQRSTUVWXYZ23456789', min_length=10, prefix='', primary_key=True, serialize=False)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Updated On')),
                ('name', models.CharField(max_length=25, verbose_name='Option Name')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('premium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalogs.premium', verbose_name='Premium')),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
    ]
