# Generated by Django 4.0.4 on 2024-02-01 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='country',
        ),
        migrations.RemoveField(
            model_name='province',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='province',
            name='updater',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
