# Generated by Django 4.0.4 on 2024-05-07 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogs', '0003_remove_province_country_remove_province_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premium',
            name='calculation_type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('MANUAL', 'Manual'), ('OPTIONS', 'Options'), ('RANGE', 'Range')], default='NORMAL', max_length=7, verbose_name='Calculation Type'),
        ),
        migrations.CreateModel(
            name='PremiumRange',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='ABCDEFGHJKMNPQRSTUVWXYZ23456789', min_length=10, prefix='', primary_key=True, serialize=False)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Updated On')),
                ('range_from', models.FloatField(verbose_name='Range From')),
                ('range_to', models.FloatField(verbose_name='Range To')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('premium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='catalogs.premium', verbose_name='Premium')),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
    ]
