# Generated by Django 4.0.4 on 2024-05-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0004_alter_premium_calculation_type_premiumrange'),
    ]

    operations = [
        migrations.AddField(
            model_name='premium',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Label'),
        ),
    ]
