# Generated by Django 4.0.4 on 2024-07-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0005_premium_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectcard',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
