# Generated by Django 4.0.4 on 2024-07-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0006_connectcard_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectcard',
            name='card_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Card ID'),
        ),
    ]
