# Generated by Django 4.0.4 on 2024-09-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authsession',
            name='device_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
